### ISSUE TITLE
Issue with C6 command when 2 modules connected

### ISSUE THREAD

**Issue by genfersee** [adfinis-sygroup/sbb-fallblatt#3] opened 2019-03-11 09:10 UTC
Hello!

I have connected 2 modules on the same RS485 bus: 1 with address 35 and the other with address 22.

The "C0" command works always great and the appropriate module moves depending on the address used in the command:
<ff c0 23 05> (Position 5 for module 35)

The "C6" command works great when I send the following command on the bus:
<ff c6 23> In that case, only module 35 moves 1 step.

But the problem comes when I send the following command on the bus:
<ff c6 16> In that case, both modules 22 and 35 move 1 step which is incorrect...
It looks like step command reacts this bad when sending to the lower address value of the 2 modules (here 22 which is <35).

How can I send a step to module 22 without having the module 35 reacting?

Do you have any idea why this behaviour? The command sent to UART seems however correct.. Did I miss something?

**Comment by karras** [comment] 2019-03-11 09:12
@eni Can you help with this one?

**Comment by eni23** [comment] 2019-03-11 09:30
Hello

This sounds like an electrical problem. The first thing you should check is if you have proper wiring and RS485 termination. Also make sure that you have an high enough voltage (over 30V), otherwise you will get weird results.

**Comment by genfersee** [comment] 2019-03-11 10:16
Thanks a lot for you very quick answer.
I am not familiar with RS485 so I did not set any termination resistor!
I will add a 120ohm termination resitor and try again. The bus installation has short wires: not longer than 50cm.

**Comment by genfersee** [comment] 2019-03-12 16:02
So I tried yesterday evening and added 120 Ohm resistors at the 2 extremities of the RS-485 bus. 

The result is the same:
- When I send command C6 to module 22 <ff c6 16>, both modules 22 and 35 are moving 1 step (incorrect)
- When I send command C6 to module 35 <ff c6 3b>, only module 35 is moving 1 step (correct)
- When I send command C0 tp module 22 <ff c0 16 05>, module 22 only moves to pos 5 (correct)

The voltage is 30.00 V and comes from a very stable power supply...

**Comment by genfersee** [comment] 2019-03-12 21:18
Ok, I investigated a bit further. I believe this is not an electrical problem since sending C0 command to each module works perfectly. And I noticed something interessant:

If I connect only module with address 22 (0x16) to the bus, and if I send:
<ff c6 17> the module 22 does not step forward (correct)
<ff c6 16> the module 22 makes 1 step forward (correct)
<ff c6 15> the module 22 makes 1 step forward (incorrect?)
<ff c6 14> the module 22 makes 1 step forward (incorrect?)
<ff c6 13> the module 22 makes 1 step forward (incorrect?)
...
Module 22 will react to C6 command for all addresses from 22 to 01. 

All Modules behaves the same. If I send a C6 command to an address lower or equal to the module address, C6 command is making step forward.
Whereas C0 command <ff c0 16 05> works perfectly and only makes effect for the exact module address.

Then, adding a second module with address 35 (0x23) to the bus:
Module 35 will react to C6 command for all addresses from 35 to 01.
Module 22 will react to C6 command for all addresses from 22 to 01. 
So both modules 35 and 22 reacts to C6 command from address 22 to 01.

Is this normal behaviour? 

Kind regards

**Comment by eni23** [comment] 2019-03-13 16:41
Hi

I just tested this behavior with our panels, and it looks like you are right, i was able to kind of reproduce this issue.

We have an array of 50 modules, addressed from 1 to 51:
* If i send `FF C6 1` every module will do a step
* If i send `FF C6 2` every module except the first will do a step
* If i send `FF C6 30` module 30 to 51 will do a step
* and so on

I was not aware of this behavior since i only used the step-command for calibrating modules and this i only did with one module on the bus. I reverse-engineered the protocol and have no access on the original docs, so this doc can have errors with such specialized usecases.
I will update them with your findings when find some time for it.

Just out of curiosity: Why do you even want to send a `STEP` command on a bus with multiple modules? If the modules are calibrated, you can normally use the `POS` command, then the module knows where it is and where it needs to go. If you just work with `STEP`-Commands, you have to track the position yourself as far i know.

**Comment by genfersee** [comment] 2019-03-13 20:19
Good to read that you have the same behaviour!
But your observation is the other way around as mine: I would have the following:
If i send FF C6 1: only module 1  will do a step
If i send FF C6 2: modules 1 and 2 will do a step
If i send FF C6 30 module 1 to 30 will do a step
and so on...

By the way I think pulse C7 and reset C4 commands are also suffering the same behaviour (would have to verify again).
 
I reused some existing code in which each module was initialised using the step command, but as  you say, I think this is useless once the module have been calibrated. I will then just modify the code to sent simple "C6 to position 0" command for each module.

If by chance you manage to find the clean way to address the C6 command to 1 module among some others, I would however be interested! ;)

Kind regards!

**Comment by eni23** [comment] 2019-11-01 10:53
Is this issue still relevant? If not i would like to close it. 

Thanks..

**Comment by genfersee** [comment] 2019-11-01 11:42
Issue is still present but not that annoying since C6 command is not that used.
You can close the issue :)

**Comment by eni23** [comment] 2019-11-01 15:14
Thanks.

**Closed by eni23** 2019-11-01 15:14 UTC
Labels: question
